### ISSUE TITLE
All procs not uploaded

### ISSUE THREAD

**Issue by Geetima2021** [binocroc/TCLWorkshop#1]
Some of the procs used in your scripts are not uploaded in the repository. It is difficult for others to use your repository for further learning.

**Comment by binocroc** [comment]
Yes ma'am, i thought i had to only upload the files that were either created or tested by me. But I now get the purpose of the repo.

**Comment by binocroc** [comment]
Yes ma'am, i thought i had to only upload the files that were either created or tested by me. But i now get the purpose of the repo.
